# -- RESERVED --
# Define your Job
Train_Dataset: TrainBlender
Val_Dataset: ValBlender
Model: PVN3D_E2E
Loss: PvnLoss
Metrics:
  - accuracy
Optimizer: Adam
Callbacks: # TO be revised
  - DemoInference
  - ModelCheckpoint
  #- ReduceLROnPlateau
  #- terminate on nan
gpus:
  - 0
model_compile:
  run_eagerly: false
model_fit:
  epochs: 20
  validation_freq: 1

# --- ---
# Define Kwargs for modules below

Adam:
  learning_rate: 0.0001
  
TrainBlender:
  batch_size: 32
  root: "/media/lukas/G-RAID/datasets/blender"
  data_name: cps
  cls_type: chew_toy
  train_split: 0.9
  #cutoff: 1000
  use_cache: true
  im_size:
    - 1080
    - 1920

ValBlender: &val_config
  batch_size: 32
  root: "/media/lukas/G-RAID/datasets/blender"
  data_name: cps
  cls_type: chew_toy
  train_split: 0.9
  #cutoff: 1000
  use_cache: true
  im_size:
    - 1080
    - 1920


PVN3D_E2E:
  resnet_input_shape: [160, 160, 3] # in 6IMPOSE: 80x80
  n_point_candidates: 10
  num_kpts: 8
  num_cpts: 1
  num_cls: 1
  dim_xyz: 3
  resnet_params:
    backbone_type: "resnet18"
    down_sample_factor: 8
    backbone_weights: ""
    interpolation_method: "nearest"
    freeze_model: false
    include_top: false
  psp_params:
    build_seg_model: false
    if_use_dropout: true
    pyramid_block_output_size: [1,2,5,10]
    pyramid_conv_kernel: [1,1]
    pyramid_conv_dim: 512
    feats_2_conv_dim: 1024
    upsample_scale: 2
    upsample_conv_kernel: [3,3]
    upsample_1_conv_dim: 256
    upsample_2_conv_dim: 64
    upsample_3_conv_dim: 64
    psp_features_dim: 128
    psp_features_conv_kernel: [1,1]
    activation: "Relu"
  point_net2_params:
    bn: false
    is_train: true
    keep_prob: 0.5
    return_features: true
    use_tf_interpolation: true
    n_sample_points: 4096
  dense_fusion_params:
    num_embeddings  : 128
    conv1d_kernel: 1
    rgb_conv1d_dim: 256
    pcl_conv1d_dim: 256
    rgbd_feats1_conv1d_dim: 512
    rgbd_feats2_conv1d_dim: 1024
  mlp_params:
    kp_conv1d_1_dim: 128
    kp_conv1d_2_dim: 64
    kp_conv1d_3_dim: 16
    cp_conv1d_1_dim: 128
    cp_conv1d_2_dim: 64
    cp_conv1d_3_dim: 16
    seg_conv1d_1_dim: 128
    seg_conv1d_2_dim: 64
    seg_conv1d_3_dim: 16


DemoInference:
  num_validate: 5
  data_cfg: *val_config


PvnLoss:
  binary_loss: True
  kp_loss_discount: 1.0
  cp_loss_discount: 1.0
  seg_loss_discount: 0.1