epochs: 50
num_validate: 5
dataset: sptfrecord # 6IMPOSE

#weights: "checkpoints/lm_cam (no-seg loss)/model_01"
#weights: "checkpoints/lm_cam (continued)/model_49"
#weights: "checkpoints/TrainE2E_Base6IMPOSE/model_13"

# weights: ...

Adam:
  learning_rate: 0.0002

shared: &shared
  root: "/home/lukas/data/6IMPOSE"
  cls_type: nema17_holder2
  data_name: test
  train_split: 0.9
  batch_size: 32
  use_cache: False
  n_aug_per_image: 1
  n_objects_per_image: 5
  bbox_noise: 20 # shift by how maximum many pixels

TrainSPTFRecord:
  <<: *shared
  #cutoff: 2 # truncate dataset for testing
  add_bbox_noise: true

ValSPTFRecord:
  <<: *shared
  #cutoff: 1000
  add_bbox_noise: false


PVN3D_E2E:
  resnet_input_shape: [80, 80, 3]
  n_point_candidates: 100
  num_kpts: 8
  num_cpts: 1
  num_cls: 1
  dim_xyz: 3
  resnet_params:
    backbone_type: "resnet34"
    down_sample_factor: 8
    backbone_weights: ""
    interpolation_method: "nearest"
    freeze_model: false
    include_top: false
  psp_params:
    build_seg_model: false
    if_use_dropout: true
    pyramid_block_output_size: [1,2,5,10]
    pyramid_conv_kernel: [1,1]
    pyramid_conv_dim: 512
    feats_2_conv_dim: 1024
    upsample_scale: 2
    upsample_conv_kernel: [3,3]
    upsample_1_conv_dim: 256
    upsample_2_conv_dim: 64
    upsample_3_conv_dim: 64
    psp_features_dim: 128
    psp_features_conv_kernel: [1,1]
    activation: "Relu"
  point_net2_params:
    bn: false
    is_train: true
    keep_prob: 0.5
    return_features: true
    use_tf_interpolation: false
    use_tfx: true # exclusively tensorflow
    n_sample_points: 512
  dense_fusion_params:
    num_embeddings: 128
    conv1d_kernel: 1
    rgb_conv1d_dim: 256
    pcl_conv1d_dim: 256
    rgbd_feats1_conv1d_dim: 512
    rgbd_feats2_conv1d_dim: 1024
  mlp_params:
    kp_conv1d_1_dim: 128
    kp_conv1d_2_dim: 64
    kp_conv1d_3_dim: 16
    cp_conv1d_1_dim: 128
    cp_conv1d_2_dim: 64
    cp_conv1d_3_dim: 16
    seg_conv1d_1_dim: 128
    seg_conv1d_2_dim: 64
    seg_conv1d_3_dim: 16

PvnLoss:
  binary_loss: True
  use_segmentation: True # default: True
  kp_loss_discount: 1.0
  cp_loss_discount: 1.0
  seg_loss_discount: 0.01
